language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=Django==1.4.2
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.6

# command to install dependencies
install:
  - pip install $DJANGO_VERSION south factory_boy

# command to run tests

script:
  - python runtests.py
